# Generated by Django 3.0.3 on 2020-08-20 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20190109_1715'),
        ('analyses', '0016_merge_20200309_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='input_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='input_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='lookup_errors_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookup_errors_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='lookup_success_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookup_success_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='lookup_validation_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lookup_validation_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='output_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='output_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='settings_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_file_analyses', to='files.RelatedFile'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='summary_levels_file',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_levels_file_analyses', to='files.RelatedFile'),
        ),
    ]
